<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://webservicespractica2.com" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="http://webservicespractica2.com" xmlns:intf="http://webservicespractica2.com" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<!--WSDL created by Apache Axis version: 1.4
Built on Apr 22, 2006 (06:55:48 PDT)-->
 <wsdl:types>
  <schema elementFormDefault="qualified" targetNamespace="http://webservicespractica2.com" xmlns="http://www.w3.org/2001/XMLSchema">
   <element name="mostrarMensajeRaro">
    <complexType/>
   </element>
   <element name="mostrarMensajeRaroResponse">
    <complexType>
     <sequence>
      <element name="mostrarMensajeRaroReturn" type="xsd:string"/>
     </sequence>
    </complexType>
   </element>
  </schema>
 </wsdl:types>

   <wsdl:message name="mostrarMensajeRaroRequest">

      <wsdl:part element="impl:mostrarMensajeRaro" name="parameters">

      </wsdl:part>

   </wsdl:message>

   <wsdl:message name="mostrarMensajeRaroResponse">

      <wsdl:part element="impl:mostrarMensajeRaroResponse" name="parameters">

      </wsdl:part>

   </wsdl:message>

   <wsdl:portType name="HolaMundoFacilito">

      <wsdl:operation name="mostrarMensajeRaro">

         <wsdl:input message="impl:mostrarMensajeRaroRequest" name="mostrarMensajeRaroRequest">

       </wsdl:input>

         <wsdl:output message="impl:mostrarMensajeRaroResponse" name="mostrarMensajeRaroResponse">

       </wsdl:output>

      </wsdl:operation>

   </wsdl:portType>

   <wsdl:binding name="HolaMundoFacilitoSoapBinding" type="impl:HolaMundoFacilito">

      <wsdlsoap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

      <wsdl:operation name="mostrarMensajeRaro">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="mostrarMensajeRaroRequest">

            <wsdlsoap:body use="literal"/>

         </wsdl:input>

         <wsdl:output name="mostrarMensajeRaroResponse">

            <wsdlsoap:body use="literal"/>

         </wsdl:output>

      </wsdl:operation>

   </wsdl:binding>

   <wsdl:service name="HolaMundoFacilitoService">

      <wsdl:port binding="impl:HolaMundoFacilitoSoapBinding" name="HolaMundoFacilito">

         <wsdlsoap:address location="http://localhost:8080/WebServicesPractica2/services/HolaMundoFacilito"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>
